/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;

import com.inf310sb.arboles.AVL;
import com.inf310sb.arboles.ArbolBinarioBusqueda;
import com.inf310sb.arboles.IArbolBusqueda;


/**
 *
 * @author HAROLD
 */

public class MENU extends javax.swing.JFrame {

    /**
     * Creates new form MENU
     */
    public MENU() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        Principio = new javax.swing.JMenuBar();
        TEMA1 = new javax.swing.JMenu();
        Crear = new javax.swing.JMenuItem();
        Cargar = new javax.swing.JMenuItem();
        Guardar = new javax.swing.JMenuItem();
        Eliminar = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        Crear1 = new javax.swing.JMenuItem();
        Cargar1 = new javax.swing.JMenuItem();
        Guardar1 = new javax.swing.JMenuItem();
        Eliminar1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        Crear2 = new javax.swing.JMenuItem();
        Cargar2 = new javax.swing.JMenuItem();
        Guardar2 = new javax.swing.JMenuItem();
        Eliminar2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Crear3 = new javax.swing.JMenuItem();
        Cargar3 = new javax.swing.JMenuItem();
        Guardar3 = new javax.swing.JMenuItem();
        Eliminar3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);

        escritorio.setToolTipText("");
        escritorio.setAutoscrolls(true);
        escritorio.setInheritsPopupMenu(true);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1088, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 834, Short.MAX_VALUE)
        );

        TEMA1.setText("ARBOL BINARIO");

        Crear.setText("Crear");
        Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearActionPerformed(evt);
            }
        });
        TEMA1.add(Crear);

        Cargar.setText("Cargar");
        Cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarActionPerformed(evt);
            }
        });
        TEMA1.add(Cargar);

        Guardar.setText("Guardar");
        TEMA1.add(Guardar);

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        TEMA1.add(Eliminar);

        Principio.add(TEMA1);

        jMenu4.setText("ARBOL MVIAS");

        Crear1.setText("Crear");
        Crear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Crear1ActionPerformed(evt);
            }
        });
        jMenu4.add(Crear1);

        Cargar1.setText("Cargar");
        Cargar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cargar1ActionPerformed(evt);
            }
        });
        jMenu4.add(Cargar1);

        Guardar1.setText("Guardar");
        jMenu4.add(Guardar1);

        Eliminar1.setText("Eliminar");
        Eliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar1ActionPerformed(evt);
            }
        });
        jMenu4.add(Eliminar1);

        Principio.add(jMenu4);

        jMenu1.setText("ARBOL MVIAS");

        Crear2.setText("Crear");
        Crear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Crear2ActionPerformed(evt);
            }
        });
        jMenu1.add(Crear2);

        Cargar2.setText("Cargar");
        Cargar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cargar2ActionPerformed(evt);
            }
        });
        jMenu1.add(Cargar2);

        Guardar2.setText("Guardar");
        jMenu1.add(Guardar2);

        Eliminar2.setText("Eliminar");
        Eliminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar2ActionPerformed(evt);
            }
        });
        jMenu1.add(Eliminar2);

        Principio.add(jMenu1);

        jMenu2.setText("ARBOL B");

        Crear3.setText("Crear");
        Crear3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Crear3ActionPerformed(evt);
            }
        });
        jMenu2.add(Crear3);

        Cargar3.setText("Cargar");
        Cargar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cargar3ActionPerformed(evt);
            }
        });
        jMenu2.add(Cargar3);

        Guardar3.setText("Guardar");
        jMenu2.add(Guardar3);

        Eliminar3.setText("Eliminar");
        Eliminar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar3ActionPerformed(evt);
            }
        });
        jMenu2.add(Eliminar3);

        Principio.add(jMenu2);

        setJMenuBar(Principio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CargarActionPerformed

    private void CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearActionPerformed
        MBinario ibinaria = new MBinario();
        escritorio.add(ibinaria);
        ibinaria.show();;
    }//GEN-LAST:event_CrearActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarActionPerformed

    private void Crear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Crear1ActionPerformed
        MAVL i = new MAVL();
        escritorio.add(ibinaria);
        ibinaria.show();;
    }//GEN-LAST:event_Crear1ActionPerformed

    private void Cargar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cargar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cargar1ActionPerformed

    private void Eliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Eliminar1ActionPerformed

    private void Crear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Crear2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Crear2ActionPerformed

    private void Cargar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cargar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cargar2ActionPerformed

    private void Eliminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Eliminar2ActionPerformed

    private void Crear3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Crear3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Crear3ActionPerformed

    private void Cargar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cargar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cargar3ActionPerformed

    private void Eliminar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Eliminar3ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Cargar;
    private javax.swing.JMenuItem Cargar1;
    private javax.swing.JMenuItem Cargar2;
    private javax.swing.JMenuItem Cargar3;
    private javax.swing.JMenuItem Crear;
    private javax.swing.JMenuItem Crear1;
    private javax.swing.JMenuItem Crear2;
    private javax.swing.JMenuItem Crear3;
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JMenuItem Eliminar1;
    private javax.swing.JMenuItem Eliminar2;
    private javax.swing.JMenuItem Eliminar3;
    private javax.swing.JMenuItem Guardar;
    private javax.swing.JMenuItem Guardar1;
    private javax.swing.JMenuItem Guardar2;
    private javax.swing.JMenuItem Guardar3;
    private javax.swing.JMenuBar Principio;
    private javax.swing.JMenu TEMA1;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    // End of variables declaration//GEN-END:variables
}
